### ISSUE TITLE
About SMD Datasets and Checkpoint

### ISSUE THREAD

**Issue by Leesangoh** [Hyon0930/DiffVel_CMMR2023#1]
Hello! I'm very impressed by your work.

I am currently trying to reproduce the result of your paper, but the SMD dataset and the latest checkpoints are inaccessible.

If you don't mind, could you please provide me the link that is accessible?

Thank you for your kindness..

**Comment by Hyon0930** [comment]
Hi, Thank you so much for your enquiry. can you please send access requests to the folders so that I can give the access to you?
